name: Hourly Proxy Checker

on:
  schedule:
    - cron: '0 * * * *'  # Запуск каждый час
  workflow_dispatch:     # Позволит запускать проверку вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: python main.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add subscription.txt
        git commit -m "Update subscription: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
        git push
        
